
language: r
# test on older versions and devel
# https://docs.travis-ci.com/user/languages/r#R-Versions
r:
  - release
  # - devel
  - 3.1
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages

matrix:
  fast_finish: true # http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
                    # allows the build to "pass" when the non-failure-able builds are done
  allow_failures: # http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
    - r: 3.1
#     - env: R_BUILD_ARGS="" R_CHECK_ARGS="--as-cran" R_CHECK_REVDEP="1" # allows the reverse depends to fail :-\


r_binary_packages:
  # install locally to avoid rev dep
  - covr # code coverage check
  - lintr # code lint

r_github_packages:
  - schloerke/travisDrat

after_success:
  - Rscript -e 'eval(parse(text = read.dcf(".helper_functions", fields = "knit_vignettes")))'
  - Rscript -e 'covr::codecov()'
  - Rscript -e "travisDrat::deploy_drat(valid_branches = 'master')"


notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis

env:
  global:
    secure: "QIlD/M810vKuXF9HwtCXoJy9FszK1EMS1NMdulEp6HXCO75eWTauDz64k8lPnMya1eu7965P54JF/IjU67rwmAi2svTQrmGwCihFlPN4h1KfcoIOXHh9XE2Am/uwn4wa5lJcDob7bm2NzDYDBEzMy6iSpURABDp6zHRaMFF7ELw="
