
language: r
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages

## default R_*_ARGS
# R_BUILD_ARGS="--no-build-vignettes" R_CHECK_ARGS="--no-manual --as-cran"
env:
  - WARNINGS_ARE_ERRORS=1

# matrix:
#   fast_finish: true # http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
#                     # allows the build to "pass" when the non-failure-able builds are done
#   allow_failures: # http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
#     - env: R_BUILD_ARGS="" R_CHECK_ARGS="--as-cran" R_CHECK_REVDEP="1" # allows the reverse depends to fail :-\

# install locally to avoid rev dep
r_github_packages:
  - jimhester/covr # code coverage check
  - jimhester/lintr # code lint

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis
