
language: r
sudo: false
cache: packages

matrix:
  fast_finish: true # http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
                    # allows the build to "pass" when the non-failure-able builds are done
  allow_failures: # http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
    - r: 3.1
    - r: devel
  # test on older versions and devel
  # https://docs.travis-ci.com/user/languages/r#R-Versions
  include:
    - r: release
      env:
        # secret key to allow for packagedocs and travisDrat
        secure: "QIlD/M810vKuXF9HwtCXoJy9FszK1EMS1NMdulEp6HXCO75eWTauDz64k8lPnMya1eu7965P54JF/IjU67rwmAi2svTQrmGwCihFlPN4h1KfcoIOXHh9XE2Am/uwn4wa5lJcDob7bm2NzDYDBEzMy6iSpURABDp6zHRaMFF7ELw="
      r_binary_packages:
        # install locally to avoid rev dep
        - covr # code coverage check
        - lintr # code lint
      r_github_packages:
        - schloerke/travisDrat
      after_success:
        - Rscript -e 'covr::codecov()'
        - CAN_PRINT=TRUE Rscript -e "packagedocs::deploy_travis(valid_branches = 'dev', push_branch = 'gh-pages-dev')"
        - CAN_PRINT=TRUE Rscript -e "packagedocs::deploy_travis(valid_branches = 'master')"
        - Rscript -e "travisDrat::deploy_drat(valid_branches = 'master', drat_repo = 'schloerke/drat')"

    # - r: 3.1
    - r: devel


notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis
