# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

env:
  global:
    - BOOTSTRAP_LATEX="1"

before_install:
  - curl -OL http://raw.github.com/schloerke/r-travis/rev_deps/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r_binary rJava igraph minqa nloptr RcppEigen colorspace reshape2 proto abind coda dichromat labeling brew gtable reshape network RColorBrewer scagnostics sna lme4 munsell arm scales ggplot2
  - ./travis-tool.sh install_deps
  - curl -OL http://cran.r-project.org/src/contrib/cairoDevice_2.20.tar.gz
  - R CMD install --no-test-load cairoDevice_2.20.tar.gz
  - rm cairoDevice_2.20.tar.gz

script:
  - R_CHECK_REVDEP=1 ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
