
language: r
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages

## default R_*_ARGS
# R_BUILD_ARGS="--no-build-vignettes" R_CHECK_ARGS="--no-manual --as-cran"
env:
  - WARNINGS_ARE_ERRORS=1

# matrix:
#   fast_finish: true # http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
#                     # allows the build to "pass" when the non-failure-able builds are done
#   allow_failures: # http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
#     - env: R_BUILD_ARGS="" R_CHECK_ARGS="--as-cran" R_CHECK_REVDEP="1" # allows the reverse depends to fail :-\

Remotes:
  - jimhester/covr  # code coverage check
  - jimhester/lintr # code lint

# r_binary_packages:
#   - arm
#   - geosphere
#   - ggmap
#   - igraph
#   # - intergraph
#   - knitr
#   - maps
#   - network
#   - RColorBrewer
#   - scagnostics
#   - scales
#   - sna
#   - survival
#   # - tnet
#   - roxygen2
#   - testthat

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: CBwdJj/j8K/o2Mv9iIhG/BtbIECU0ZA8BODtWA2YmDzja8BJOFKdFCtp1t+KeNV4BAZ1oUaDK4ETNgRirh/YZwobxsfK+AzQwZWzBI4WY6WAnBZpUteKNrsTCyTD0vZKYwWc7IFtEAUQBdsWr4PU+kGGKQ3aUhwsZ85QF9x/nHY=

branches:
  only:
    - master
    - dev
    - travis
